version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
    networks:
      - nginx

  app:
    build: app
    expose:
      - "8080"
    networks:
      - nginx
networks:
  nginx:
